package hibernatemodels;
// Generated Feb 8, 2015 11:44:14 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String rname;
     private String rsurname;
     private String email;
     private String phone;
     private String country;
     private String city;
     private String address;
     private String organization;
     private String username;
     private String password;
     private String nickname;

    public User() {
    }

	
    public User(String rname, String rsurname, String email, String country, String username, String password) {
        this.rname = rname;
        this.rsurname = rsurname;
        this.email = email;
        this.country = country;
        this.username = username;
        this.password = password;
    }
    public User(String rname, String rsurname, String email, String phone, String country, String city, String address, String organization, String username, String password, String nickname) {
       this.rname = rname;
       this.rsurname = rsurname;
       this.email = email;
       this.phone = phone;
       this.country = country;
       this.city = city;
       this.address = address;
       this.organization = organization;
       this.username = username;
       this.password = password;
       this.nickname = nickname;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRname() {
        return this.rname;
    }
    
    public void setRname(String rname) {
        this.rname = rname;
    }
    public String getRsurname() {
        return this.rsurname;
    }
    
    public void setRsurname(String rsurname) {
        this.rsurname = rsurname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(String organization) {
        this.organization = organization;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }




}


